#!/usr/bin/env python3
import jwt
import json

# The JWT token generated by our test
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic2NvcGUiOiJyZWFkIn0.n0H69fPFmArF5kxw1QfzjarkZUNj0SHokztnomwoTGo"

# Decode without verification to see the payload
try:
    decoded = jwt.decode(token, options={"verify_signature": False})
    print("Decoded JWT payload:")
    print(json.dumps(decoded, indent=2))
except Exception as e:
    print(f"Error decoding JWT: {e}")

# Try to verify with the secret
try:
    verified = jwt.decode(token, "myfancysecret", algorithms=["HS256"])
    print("\nVerified JWT payload:")
    print(json.dumps(verified, indent=2))
except Exception as e:
    print(f"Error verifying JWT: {e}")